import turtle as t

t.penup()
t.goto(50, 100)
t.write("Myanmar")
t.penup()
t.goto(-250, 100)
t.pendown()
t.fillcolor("yellow")
t.begin_fill()
for i in range(2):
    t.forward(300)
    t.left(90)
    t.forward(50)
    t.left(90)
t.end_fill()
t.penup()
t.goto(-250, 50)
t.pendown()
t.fillcolor("green")
t.begin_fill()
for i in range(2):
    t.forward(300)
    t.left(90)
    t.forward(50)
    t.left(90)
t.end_fill()
t.penup()
t.goto(-250, 0)
t.pendown()
t.fillcolor("red")
t.begin_fill()
for i in range(2):
    t.forward(300)
    t.left(90)
    t.forward(50)
    t.left(90)
t.end_fill()
t.penup()
t.goto(-145, 100)
t.pendown()
t.fillcolor("white")
t.begin_fill()
for i in range(5):
    t.forward(100)
    t.right(144)
t.end_fill()
t.done()